export const FETCH_RECENT_PHOTOS_START = 'FETCH_RECENT_PHOTOS_START';
export const FETCH_RECENT_PHOTOS_SUCCESS = 'FETCH_RECENT_PHOTOS_SUCCESS';
export const FETCH_RECENT_PHOTOS_FAIL = 'FETCH_RECENT_PHOTOS_FAIL';
